### ISSUE TITLE
Not able to run project for learning purpose

### ISSUE THREAD

**Issue by sanjeevbishnoi** [zakariaBoukernafa/GraphQL-keystone-API#1]
Please provide .keystone. file or keystone.example file so that I can run project.

import { CartItemCreateInput } from '../.keystone/schema-types'; is giving file not found error.

**Comment by zakariaBoukernafa** [comment]
.keystone is a folder that is generated after running the project, make sure that you install the npm dependencies and then run the project.

you may need to delete ".keystone" folder, clear the cache and then run the project again.

**Comment by sanjeevbishnoi** [comment]
Will try, Thanks a lot.
